#ifndef IDC_STATIC
#define IDC_STATIC (-1)
#endif

#define IDB_FLIPSIDE                            99
#define IDB_CARD1                               100
#define IDB_CARD2                               101
#define IDB_CARD3                               102
#define IDB_CARD4                               103
#define IDB_CARD5                               104
#define IDB_CARD6                               105
#define IDB_CARD7                               106
#define IDB_CARD8                               107
#define IDB_CARD9                               108
#define IDB_CARD10                              109
#define IDB_CARD11                              110
#define IDB_CARD12                              111
#define IDB_CARD13                              112
#define IDB_CARD14                              113
#define IDB_CARD15                              114
#define IDB_CARD16                              115
#define IDB_CARD17                              116
#define IDB_CARD18                              117
#define IDB_CARD19                              118
#define IDB_CARD20                              119
#define IDB_CARD21                              120
#define IDB_CARD22                              121
#define IDB_CARD23                              122
#define IDB_CARD24                              123
#define IDB_CARD25                              124
#define IDB_CARD26                              125
#define IDB_CARD27                              126
#define IDB_CARD28                              127
#define IDB_CARD29                              128
#define IDB_CARD30                              129
#define IDB_CARD31                              130
#define IDB_CARD32                              131
#define IDB_CARD33                              132
#define IDB_CARD34                              133
#define IDB_CARD35                              134
#define IDB_CARD36                              135
#define IDB_CARD37                              136
#define IDB_CARD38                              137
#define IDB_CARD39                              138
#define IDB_CARD40                              139
#define IDB_CARD41                              140
#define IDB_CARD42                              141
#define IDB_CARD43                              142
#define IDB_CARD44                              143
#define IDB_CARD45                              144
#define IDB_CARD46                              145
#define IDB_CARD47                              146
#define IDB_CARD48                              147
#define IDB_CARD49                              148
#define IDB_CARD50                              149
#define IDB_CARD51                              150
#define IDB_CARD52                              151

#define MANIFEST                                200
#define VERSION                                 201
#define IDI_ICON                                203
#define IDR_MENU                                204
#define IDD_CONFIG                              205

#define IDM_NOVO                                40000
#define IDM_SOBRE                               40001
#define IDM_SAIR                                40002
#define IDM_CONFIG                              40003
#define IDC_BLIND                               40004
#define IDC_MONEY                               40005
#define IDC_UPBLIND                             40006
#define IDC_NUMPLAYERS                          40007

#define IDB_ALLIN                               10
#define IDB_RAISE                               11
#define IDB_FOLD                                12
#define IDB_CONTINUE                            13
